# Generated by Django 4.2.4 on 2023-09-01 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.BinaryField()),
                ('decryptKey', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=355)),
                ('senderName', models.CharField(max_length=355)),
                ('contentName', models.CharField(max_length=100)),
                ('CuratorName', models.CharField(max_length=355)),
                ('uploadDate', models.DateTimeField()),
                ('CuratorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.curator', verbose_name='Curator ID')),
                ('semesterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.content', verbose_name='Semester ID')),
            ],
        ),
    ]
