# Generated by Django 4.2.4 on 2023-09-01 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_file_curatorid_alter_file_semesterid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.BinaryField()),
                ('decryptKey', models.BinaryField()),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='CuratorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.curator', verbose_name='Curator ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='semesterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.content', verbose_name='Semester ID'),
        ),
    ]
