# Generated by Django 4.2.4 on 2023-09-01 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_content_curator_alter_file_curatorid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='curator',
            name='decryptKey',
        ),
        migrations.RemoveField(
            model_name='file',
            name='CuratorName',
        ),
        migrations.RemoveField(
            model_name='file',
            name='semesterID',
        ),
        migrations.AlterField(
            model_name='curator',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='Semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models.semester', verbose_name='Semester ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.semester', verbose_name='Semester Value'),
        ),
    ]
