# Generated by Django 4.2.4 on 2023-09-01 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_remove_file_semester_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.content', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='file',
            name='Curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.curator', verbose_name='Curator'),
        ),
    ]
