# Generated by Django 4.2.4 on 2023-09-01 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_file_content_alter_file_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models.semester', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='Content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.content', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='Curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.curator', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='contentName',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=355, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='senderName',
            field=models.CharField(max_length=355, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploadDate',
            field=models.DateTimeField(verbose_name=''),
        ),
    ]
