# Generated by Django 4.2.4 on 2023-09-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_file_semester_alter_file_content_alter_file_curator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='contentName',
        ),
    ]
