# Generated by Django 4.2.4 on 2023-09-05 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_rename_content_file_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.semester', verbose_name=''),
        ),
    ]
