# Generated by Django 4.2.4 on 2023-09-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_rename_sendername_file_sender_remove_file_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploadDate',
            field=models.DateField(verbose_name=''),
        ),
    ]
